### ISSUE TITLE
Presets merging logic: key `purge` should be replaced by `content` and `safelist`

### ISSUE THREAD

**Issue by mpsijm** [tailwindlabs/tailwindcss.com#1084]
The following section in the documentation is outdated since the release of v3: https://tailwindcss.com/docs/presets#how-configurations-are-merged

It states:
> The following options in tailwind.config.js simply replace the same option if present in a preset:
> - `purge`
> - ...

However, as stated in https://tailwindcss.com/docs/upgrade-guide#configure-content-sources, the `purge` option is replaced by `content` and `safelist`.

I'm currently assuming that the "replacement" strategy still holds for these new keys, but it can't hurt to know the exact behaviour :smile:

**Comment by simonswiss** [comment]
Just checked the live site and it looks like this has been fixed by this PR:

**Comment by mpsijm** [comment]
It's not entirely fixed though, because the [Merging logic in-depth](https://tailwindcss.com/docs/presets#merging-logic-in-depth) section still does not mention the `safelist` option :thinking:
