### ISSUE TITLE
ring in input text is not working on iOS Safari

### ISSUE THREAD

**Issue by smoothdvd** [tailwindlabs/tailwindcss.com#1135]
**What version of Tailwind CSS are you using?**

3.0.13

**What build tool (or framework if it abstracts the build tool) are you using?**

Nextjs 12.0.7, postcss ^8.4.5

**What version of Node.js are you using?**

v14.x / v16.x

**What browser are you using?**

iOS 15.2 Safari

**What operating system are you using?**

iOS 15.2

**Reproduction URL**

https://tailwindcss.com homepage, State variants section

**Describe your issue**

ring and ring-color in input text (project filter) is not working on iOS Safari, there is no border on normal state and not ring-color on  focus state.

iOS 15.2, Safari:
![IMG_2472](https://user-images.githubusercontent.com/22420/149247332-cc35c169-77be-494b-9bce-88f2205bc7e9.jpeg)

macOS 12.1, Safari
<img width="324" alt="Screen Shot 2022-01-13 at 8 46 22 AM" src="https://user-images.githubusercontent.com/22420/149247392-f27e38eb-2172-45c7-abbf-6e57e14783f3.png">

**Comment by reinink** [comment]
Hey thanks for reporting this!

I have corrected this issue: 646088218af320414d038432ee96394335544f19

We need to add `appearance-none` to this input, as Safari on iOS adds a drop shadow to inputs, which was overriding our ring utility.

Thanks again! 👍

**Comment by smitpatelx** [comment]
What about buttons? `appearance-none` doesn’t work on buttons. Please help

**Comment by lakessyde** [comment]
I am still having this issuse used ring-1 on input filed work fine on the os expect ios even on ios 15

**Comment by kylesloper** [comment]
Experiencing this same problem relating to buttons. The default drop shadow overrides any ring set. Has this not been fixed yet?

**Comment by vincentwinkel** [comment]
Same problem here on Safari macbook pro:

<img width="800" alt="Screenshot 2023-03-14 at 09 22 28" src="https://user-images.githubusercontent.com/1402505/224940933-d37f4f38-404d-4b38-b358-ec68b6d42e4f.png">

**Comment by deviationist** [comment]
I got the same issue - ring not working on iOS Safari. I set up a clean Next.js 13-project, add Tailwind according to docs, insert boilerplate input-field from TailwindUI, no border/ring at all.

**Comment by soundsystems** [comment]
Any workaround for adding a ring to a button with input field? (ie. Subscribe Now for email list)

**Comment by supermar1010** [comment]
@soundsystems @deviationist I just tried adding appearance-none to the input element. This made the ring work :)

**Comment by Nasmar** [comment]
I'm still encountering this issue on an iPad running iOS 15.7.8. On FOCUS state it works with a blue ring.

Interestingly, it functions properly in Safari 16.5 on a Mac. However, this presents an issue, as the "ring" feature is essential for input fields in Tailwind UI.

I'm currently utilizing TailwindCSS version 3.3.3.

HTML from this TailwindUI component [https://tailwindui.com/components/application-ui/forms/sign-in-forms](url)
Sign-in and Registration
Simple
Vue
